// <auto-generated />
using System;
using Collage.WF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace College.WF.Migrations
{
    [DbContext(typeof(EFAppContext))]
    [Migration("20260313182809_InitialCommit")]
    partial class InitialCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Collage.WF.Data.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Duration = 40,
                            InstructorId = 1,
                            Name = "C# Programming"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Duration = 30,
                            InstructorId = 2,
                            Name = "Database Systems"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Duration = 35,
                            InstructorId = 3,
                            Name = "Linear Algebra"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 3,
                            Duration = 25,
                            InstructorId = 4,
                            Name = "Quantum Mechanics"
                        });
                });

            modelBuilder.Entity("Collage.WF.Data.Models.CourseSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Date = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            Title = "Intro to C#"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Date = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            Title = "OOP Basics"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            Date = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 2,
                            Title = "SQL Fundamentals"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 3,
                            Date = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 3,
                            Title = "Vectors & Matrices"
                        });
                });

            modelBuilder.Entity("Collage.WF.Data.Models.CourseSessionAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseSessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseSessionAttendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseSessionId = 1,
                            Grade = 85,
                            Notes = "Good participation",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseSessionId = 1,
                            Grade = 90,
                            Notes = "Excellent",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseSessionId = 2,
                            Grade = 78,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 4,
                            CourseSessionId = 2,
                            Grade = 92,
                            Notes = "Outstanding",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 5,
                            CourseSessionId = 3,
                            Grade = 88,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 6,
                            CourseSessionId = 3,
                            Grade = 70,
                            Notes = "Needs improvement",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 7,
                            CourseSessionId = 4,
                            Grade = 95,
                            Notes = "Top of class",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 8,
                            CourseSessionId = 4,
                            Grade = 82,
                            StudentId = 5
                        });
                });

            modelBuilder.Entity("Collage.WF.Data.Models.CourseStudent", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Course_Student", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            CourseId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            CourseId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            CourseId = 2,
                            StudentId = 2
                        },
                        new
                        {
                            CourseId = 2,
                            StudentId = 4
                        },
                        new
                        {
                            CourseId = 3,
                            StudentId = 3
                        },
                        new
                        {
                            CourseId = 3,
                            StudentId = 5
                        },
                        new
                        {
                            CourseId = 4,
                            StudentId = 1
                        },
                        new
                        {
                            CourseId = 4,
                            StudentId = 5
                        });
                });

            modelBuilder.Entity("Collage.WF.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasFilter("[ManagerId] IS NOT NULL");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Building A",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Building B",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Building C",
                            Name = "Physics"
                        });
                });

            modelBuilder.Entity("Collage.WF.Data.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FirstName = "Ahmed",
                            LastName = "Ali",
                            Phone = "0100000001"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            FirstName = "Sara",
                            LastName = "Hassan",
                            Phone = "0100000002"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            FirstName = "Mohamed",
                            LastName = "Nour",
                            Phone = "0100000003"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 3,
                            FirstName = "Fatma",
                            LastName = "Salem",
                            Phone = "0100000004"
                        });
                });

            modelBuilder.Entity("Collage.WF.Data.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Omar",
                            LastName = "Khaled",
                            Phone = "0110000001"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Nada",
                            LastName = "Ibrahim",
                            Phone = "0110000002"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Youssef",
                            LastName = "Tarek",
                            Phone = "0110000003"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Mona",
                            LastName = "Adel",
                            Phone = "0110000004"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Ali",
                            LastName = "Mostafa",
                            Phone = "0110000005"
                        });
                });

            modelBuilder.Entity("Collage.WF.Data.Models.Course", b =>
                {
                    b.HasOne("Collage.WF.Data.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Collage.WF.Data.Models.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Collage.WF.Data.Models.CourseSession", b =>
                {
                    b.HasOne("Collage.WF.Data.Models.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Collage.WF.Data.Models.Instructor", "Instructor")
                        .WithMany("CourseSessions")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Collage.WF.Data.Models.CourseSessionAttendance", b =>
                {
                    b.HasOne("Collage.WF.Data.Models.CourseSession", "CourseSession")
                        .WithMany("Attendances")
                        .HasForeignKey("CourseSessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Collage.WF.Data.Models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourseSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Collage.WF.Data.Models.CourseStudent", b =>
                {
                    b.HasOne("Collage.WF.Data.Models.Course", "Course")
                        .WithMany("CourseStudents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Collage.WF.Data.Models.Student", "Student")
                        .WithMany("CourseStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Collage.WF.Data.Models.Department", b =>
                {
                    b.HasOne("Collage.WF.Data.Models.Instructor", "Manager")
                        .WithOne("ManagedDepartment")
                        .HasForeignKey("Collage.WF.Data.Models.Department", "ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Collage.WF.Data.Models.Instructor", b =>
                {
                    b.HasOne("Collage.WF.Data.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Collage.WF.Data.Models.Course", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("CourseStudents");
                });

            modelBuilder.Entity("Collage.WF.Data.Models.CourseSession", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("Collage.WF.Data.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("Collage.WF.Data.Models.Instructor", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("Courses");

                    b.Navigation("ManagedDepartment");
                });

            modelBuilder.Entity("Collage.WF.Data.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("CourseStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
